In [179]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [208]:
labels = np.array([0,0,2,3,4,5,1])
features = np.array([
    [1, 3, 2, 4, 5],
    [2, 4, 5, 6, 7],
    [3, 5, 6, 7, 8],
    [4, 6, 7, 8, 9],
    [5, 7, 8, 9, 10],
    [6, 8, 9, 10, 11],
    [7, 9, 10, 11, 12]
])
labels

array([0, 0, 2, 3, 4, 5, 1])

In [218]:
features = np.load("pose_features.npy",allow_pickle=True)
labels = np.load("pose_labels.npy",allow_pickle=True)

In [209]:
label_to_index = {label: idx for idx, label in enumerate(np.unique(labels))}
label_to_index


{0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5}

In [198]:
index_to_label = {idx: label for label, idx in label_to_index.items()}
index_to_label

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7}

In [199]:
labels_encoded = np.array([label_to_index[label] for label in labels])
labels_encoded

array([0, 1, 2, 3, 4, 5, 6])

In [219]:
features = features.reshape((features.shape[0], 1, features.shape[1]))

ValueError: cannot reshape array of size 145530 into shape (231,1,15)

In [185]:
features.shape

(7, 1, 5)

In [231]:
# Define the LSTM model
model = Sequential()
model.add(LSTM(units=50, input_shape=(features.shape[1], features.shape[2])))
model.add(Dense(units=len(np.unique(labels)), activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


In [232]:
model.fit(features, labels, epochs=40, batch_size=1)


Epoch 1/40
231/231 [==============================] - 2s 3ms/step - loss: 1.0488 - accuracy: 0.4848
Epoch 2/40
231/231 [==============================] - 1s 3ms/step - loss: 0.7984 - accuracy: 0.6883
Epoch 3/40
231/231 [==============================] - 1s 3ms/step - loss: 0.9144 - accuracy: 0.6104
Epoch 4/40
231/231 [==============================] - 1s 2ms/step - loss: 0.6377 - accuracy: 0.7706
Epoch 5/40
231/231 [==============================] - 1s 3ms/step - loss: 0.4585 - accuracy: 0.8225
Epoch 6/40
231/231 [==============================] - 1s 3ms/step - loss: 0.2692 - accuracy: 0.8831
Epoch 7/40
231/231 [==============================] - 1s 3ms/step - loss: 0.2834 - accuracy: 0.8831
Epoch 8/40
231/231 [==============================] - 1s 3ms/step - loss: 0.1418 - accuracy: 0.9567
Epoch 9/40
231/231 [==============================] - 1s 3ms/step - loss: 0.2496 - accuracy: 0.9004
Epoch 10/40
231/231 [==============================] - 1s 3ms/step - loss: 0.1782 - accuracy: 0.9524

In [234]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [233]:
model.save("Pose_model_1")

INFO:tensorflow:Assets written to: Pose_model_1\assets


INFO:tensorflow:Assets written to: Pose_model_1\assets


In [236]:
# Evaluate the model
loss, accuracy = model.evaluate(features, labels)
print(f"Loss: {loss}, Accuracy: {accuracy}")

8/8 [==============================] - 0s 2ms/step - loss: 0.0124 - accuracy: 1.0000
Loss: 0.01242074090987444, Accuracy: 1.0


In [121]:
# Reshape the input for prediction (samples, time steps, features)
input_sequence = np.array([[2, 4, 5, 6, 7]])
input_sequence = input_sequence.reshape((input_sequence.shape[0], 1, input_sequence.shape[1]))

# Make predictions
predictions = model.predict(input_sequence)
predicted_labels = [index_to_label[np.argmax(prediction)] for prediction in predictions]
print("Predicted Labels:", predicted_labels)


1/1 [==============================] - 0s 251ms/step
Predicted Labels: ['mayank']


In [174]:
labels = np.array(["mayank", "punyay", "mayank", "manoj", "urmila", "punyay", "manoj"])
features = [
    [
        [1,2,3],
        [2,3,4],
        [3,4,5],
        [4,5,6],
        [5,6,7]
    ],
    [
        [2,3,4],
        [3,4,5],
        [4,5,6],
        [5,6,7],
        [6,7,8]
    ],
    [
        [3,4,5],
        [4,5,6],
        [5,6,7],
        [6,7,8],
        [7,8,9]
    ],
    [
        [4,5,6],
        [5,6,7],
        [6,7,8],
        [7,8,9],
        [8,9,10]
    ],
    [
        [5,6,7],
        [6,7,8],
        [7,8,9],
        [8,9,10],
        [9,10,11]
    ],
    [
        [6,7,8],
        [7,8,9],
        [8,9,10],
        [9,10,11],
        [10,11,12]
    ],
    [
        [7,8,9],
        [8,9,10],
        [9,10,11],
        [10,11,12],
        [11,12,13]
    ]
]

In [175]:
label_to_index = {label: idx for idx, label in enumerate(np.unique(labels))}
index_to_label = {idx: label for label, idx in label_to_index.items()}
labels_encoded = np.array([label_to_index[label] for label in labels])

In [176]:
label_to_index

{'manoj': 0, 'mayank': 1, 'punyay': 2, 'urmila': 3}

In [178]:
features = np.array(features)
labels_encoded

array([1, 2, 1, 0, 3, 2, 0])

In [126]:
# Define the LSTM model
model = Sequential()
model.add(LSTM(units=50, input_shape=(features.shape[1], features.shape[2])))
model.add(Dense(units=len(np.unique(labels)), activation='softmax'))

In [127]:
# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [128]:
# Train the model
model.fit(features, labels_encoded, epochs=100, batch_size=1)

Epoch 1/100
7/7 [==============================] - 1s 2ms/step - loss: 1.5054 - accuracy: 0.2857
Epoch 2/100
7/7 [==============================] - 0s 2ms/step - loss: 1.4251 - accuracy: 0.2857
Epoch 3/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3827 - accuracy: 0.2857
Epoch 4/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3764 - accuracy: 0.2857
Epoch 5/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3550 - accuracy: 0.2857
Epoch 6/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3342 - accuracy: 0.2857
Epoch 7/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3257 - accuracy: 0.2857
Epoch 8/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3337 - accuracy: 0.2857
Epoch 9/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3119 - accuracy: 0.2857
Epoch 10/100
7/7 [==============================] - 0s 2ms/step - loss: 1.3036 - accuracy: 0.4286
Epoch 11/100
7/7 [===========

In [129]:
# Evaluate the model
loss, accuracy = model.evaluate(features, labels_encoded)
print(f"Loss: {loss}, Accuracy: {accuracy}")

1/1 [==============================] - 0s 299ms/step - loss: 0.7642 - accuracy: 0.7143
Loss: 0.7642003893852234, Accuracy: 0.7142857313156128


In [130]:
# Make predictions
predictions = model.predict(features)
predicted_labels = [index_to_label[np.argmax(prediction)] for prediction in predictions]
print("Predicted Labels:", predicted_labels)

1/1 [==============================] - 0s 248ms/step
Predicted Labels: ['mayank', 'mayank', 'mayank', 'manoj', 'urmila', 'manoj', 'manoj']


In [131]:
features = [
    [
        [1,2,3],
        [2,3,4],
        [3,4,5],
        [4,5,6],
        [5,6,7]
    ],
    [
        [2,3,4],
        [3,4,5],
        [4,5,6],
        [5,6,7],
        [6,7,8]
    ],
    [
        [3,4,5],
        [4,5,6],
        [5,6,7],
        [6,7,8],
        [7,8,9]
    ],
    [
        [4,5,6],
        [5,6,7],
        [6,7,8],
        [7,8,9],
        [8,9,10]
    ],
    [
        [5,6,7],
        [6,7,8],
        [7,8,9],
        [8,9,10],
        [9,10,11]
    ],
    [
        [6,7,8],
        [7,8,9],
        [8,9,10],
        [9,10,11],
        [10,11,12]
    ],
    [
        [7,8,9],
        [8,9,10],
        [9,10,11],
        [10,11,12],
        [11,12,13]
    ]
] 

np.save('features.npy', features)


In [132]:
import h5py

with h5py.File('features.h5', 'w') as hf:
    hf.create_dataset('features', data=features)


In [133]:
features = [
    [
        [1,2,3],
        [2,3,4],
        [3,4,5],
        [4,5,6],
        [5,6,7]
    ],
    [
        [2,3,4],
        [3,4,5],
        [4,5,6],
        [5,6,7],
        [6,7,8]
    ],
    [
        [3,4,5],
        [4,5,6],
        [5,6,7],
        [6,7,8],
        [7,8,9]
    ],
    [
        [4,5,6],
        [5,6,7],
        [6,7,8],
        [7,8,9],
        [8,9,10]
    ],
    [
        [5,6,7],
        [6,7,8],
        [7,8,9],
        [8,9,10],
        [9,10,11]
    ],
    [
        [6,7,8],
        [7,8,9],
        [8,9,10],
        [9,10,11],
        [10,11,12]
    ],
    [
        [7,8,9],
        [8,9,10],
        [9,10,11],
        [10,11,12],
        [11,12,13]
    ]
] 




In [134]:
import pandas as pd
data = {
    "t1":[[1,2,3],[2,1,3],[1,2,3]],
       "t2": [[2,3,4],[2,1,3],[1,2,3]],
        "t3" :[[3,4,5],[2,1,3],[1,2,3]],
        "t4":[ [4,5,6],[2,1,3],[1,2,3]],
        "t5":[[5,6,7],[2,1,3],[1,2,3]]
}

new_data = pd.DataFrame(data)
new_data.to_csv("hello.csv" , index=False)

In [135]:

# Read the CSV file with a custom converter
converters = {'t1': ast.literal_eval, 't2': ast.literal_eval, 't3': ast.literal_eval, 't4': ast.literal_eval, 't5': ast.literal_eval}
old_data = pd.read_csv("hello.csv", converters=converters)

print(old_data)

          t1         t2         t3         t4         t5
0  [1, 2, 3]  [2, 3, 4]  [3, 4, 5]  [4, 5, 6]  [5, 6, 7]
1  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]
2  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]


In [136]:
import ast 
# Convert string representations of lists to actual lists
converted_data = [ast.literal_eval(value) for value in old_data.values]

print(converted_data)

ValueError: malformed node or string: array([list([1, 2, 3]), list([2, 3, 4]), list([3, 4, 5]), list([4, 5, 6]),
       list([5, 6, 7])], dtype=object)

In [ ]:
for col in old_data.to_records:
    df[col] = df[col].apply(ast.literal_eval)

# Convert DataFrame to a list of lists
result_list = df.values.tolist()

print(result_list)

TypeError: 'method' object is not iterable

In [ ]:
# Find the maximum length of lists across all 't' columns
# converters = {'t1': ast.literal_eval, 't2': ast.literal_eval, 't3': ast.literal_eval, 't4': ast.literal_eval, 't5': ast.literal_eval}
old_data = pd.read_csv("hello.csv") #, converters=converters)

print(old_data)
max_length = max(len(lst) for lst in old_data.values())

# Create the desired format
result_list = [
    [old_data[f't{i+1}'][j] if j < len(old_data[f't{i+1}']) else old_data[f't{i+1}'][-1] for j in range(max_length)]
    for i in range(len(old_data))
]

print(result_list)

          t1         t2         t3         t4         t5
0  [1, 2, 3]  [2, 3, 4]  [3, 4, 5]  [4, 5, 6]  [5, 6, 7]
1  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]


TypeError: 'numpy.ndarray' object is not callable

In [137]:
import pandas as pd
import ast

# Fetch data from CSV and create a DataFrame
csv_file_path = "hello.csv"
df = pd.read_csv(csv_file_path)

# Apply ast.literal_eval to each column with error handling
for col in df.columns:
    df[col] = df[col].apply(lambda x: ast.literal_eval(x) if pd.notna(x) and x.strip().startswith('[') else x)

print("Original DataFrame:")
print(df)

# Find the maximum length of lists across all columns
max_length = max(len(lst) for lst in df.dropna().values)

# Create the desired format
result_list = [
    [df[col].iloc[j] if j < len(df[col].dropna()) else None for col in df.columns]
    for j in range(max_length)
]

# Flatten the result list
result_list = [item for sublist in result_list for item in sublist]

print("\nDesired Format:")
print(result_list)


Original DataFrame:
          t1         t2         t3         t4         t5
0  [1, 2, 3]  [2, 3, 4]  [3, 4, 5]  [4, 5, 6]  [5, 6, 7]
1  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]  [2, 1, 3]
2  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]  [1, 2, 3]

Desired Format:
[[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [2, 1, 3], [2, 1, 3], [2, 1, 3], [2, 1, 3], [2, 1, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3], None, None, None, None, None, None, None, None, None, None]


In [138]:
import numpy as np

features = [
    [
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7]
    ],
    [
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7],
        [6, 7, 8]
    ],
    [
        [3, 4, 5],
        [4, 5, 6],
        [5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]
    ],
    [
        [4, 5, 6],
        [5, 6, 7],
        [6, 7, 8],
        [7, 8, 9],
        [8, 9, 10]
    ],
    [
        [5, 6, 7],
        [6, 7, 8],
        [7, 8, 9],
        [8, 9, 10],
        [9, 10, 11]
    ],
    [
        [6, 7, 8],
        [7, 8, 9],
        [8, 9, 10],
        [9, 10, 11],
        [10, 11, 12]
    ],
    [
        [7, 8, 9],
        [8, 9, 10],
        [9, 10, 11],
        [10, 11, 12],
        [11, 12, 13]
    ]
]

# Convert the list of lists to a NumPy array
features_array = np.array(features)

# Save the array to a .npy file
np.save('features.npy', features_array)


In [141]:
loaded_features = np.load('features.npy')
print(loaded_features)


[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]
  [ 4  5  6]
  [ 5  6  7]]

 [[ 2  3  4]
  [ 3  4  5]
  [ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]
  [ 7  8  9]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]
  [ 7  8  9]
  [ 8  9 10]]

 [[ 5  6  7]
  [ 6  7  8]
  [ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]

 [[ 6  7  8]
  [ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]
  [10 11 12]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]
  [10 11 12]
  [11 12 13]]]


In [142]:
import numpy as np

features = [
    1,2,3
]

# Convert the list of lists to a NumPy array
features_array = np.array(features)

# Save the array to a .npy file
np.save('features1.npy', features_array)


In [157]:
loaded_features = np.load('features1.npy', allow_pickle=True)
print(type(loaded_features))


<class 'numpy.ndarray'>


In [158]:
data = np.concatenate([loaded_features , [4,5,6]])
print(type(data))
np.save('features1.npy', data)

<class 'numpy.ndarray'>


In [4]:
import numpy as np
loaded_features = np.load('pose_labels.npy', allow_pickle=True)
print(len(loaded_features))
print(loaded_features)


624
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 

In [171]:
loaded_features = np.load('pose_features.npy', allow_pickle=True)
print(len(loaded_features))
print(loaded_features)
loaded_features.shape

231
[[[0.91689324 0.88787377 0.86680961 ... 0.60480976 1.01863015 0.57546812]
  [0.90945721 0.89461374 0.86353743 ... 0.61108655 1.01030397 0.58668685]
  [0.88326567 0.83464479 0.83037531 ... 0.54908478 0.99916035 0.51383942]
  ...
  [0.75484669 0.71731478 0.69350672 ... 0.41872653 0.80342561 0.38075188]
  [0.756607   0.71772152 0.69441348 ... 0.42092243 0.80210215 0.3863917 ]
  [0.73465675 0.73654169 0.66891629 ... 0.43275833 0.76846826 0.39500064]]

 [[0.73186767 0.73652393 0.66831857 ... 0.43150565 0.76934302 0.3925156 ]
  [0.71503079 0.74929613 0.650491   ... 0.44451922 0.74058765 0.40505832]
  [0.71579719 0.74992037 0.6507327  ... 0.44321224 0.74237609 0.40472537]
  ...
  [0.7635088  0.73931974 0.70394099 ... 0.44943175 0.83472484 0.41241699]
  [0.78153324 0.74004954 0.72358429 ... 0.45860407 0.86058623 0.41949815]
  [0.79497969 0.74803197 0.73832268 ... 0.46918955 0.88456273 0.43049663]]

 [[0.79141116 0.748366   0.73724729 ... 0.47296962 0.88885987 0.43561074]
  [0.8068772  0.75

(231, 15, 42)